### ISSUE TITLE
Keep backups of data in multiple locations

### ISSUE THREAD

**Issue by karawoo** [emhart/10-simple-rules-data-storage#10]
This applies to data at multiple stages of sharing/publishing and encompasses a spectrum from backing up files on your laptop to choosing data repositories that will keep copies of your data in different places.

**Comment by naupaka** [comment]
**Corollary 1:** All hard drives will fail, usually when you need them most. Especially spinning platters. Especially spinning platters in laptops.
**Corollary 2:** The cloud is not failsafe; data can disappear there too (see e.g. [the sad case of Dedoose and Microsoft Azure](https://www.insidehighered.com/news/2014/05/16/dedoose-crash-shows-dangers-handing-data-cloud-services)).

**Comment by dlebauer** [comment]
> usually when you need them most.

Sounds like a theory without mechanism. I can imagine 'when you need them
most' == 'when you are pushing them the hardest' ... or 'when you need them
most' == 'makes a memorable story"

Is there any evidence or is this just a precautionary saying?

**Comment by naupaka** [comment]
More of a precautionary saying - in line with never trusting that your hardware won't fail. It is true though (at least in my repeated experience) that blocks on a drive that are not used regularly will go bad and not get marked as such, and then when you start using the drive actively again, and add additional data or move things around, data will get corrupted. I've done randomized read time trials across all blocks on several of my backup drives, and this pattern is consistently observed (higher % of bad blocks in unused sectors since they aren't used regularly). Of course, YMMV, but generally high usage on an old drive is more likely to lead to failure, other things being equal.  [Some stats/data on this in a paper from Google](http://static.usenix.org/event/fast07/tech/full_papers/pinheiro/pinheiro_html/).

**Comment by emhart** [comment]
So this relates in some ways to the notion of "uniquely identifiable" in #9 .  Is uniquely identified just a specific version of the data, or is a pointer to both data and location?

Also, if you deposit your data and that repository is backed-up, do you trust that back-up?  Or do you maintain both a repository version and your own backed up version?

**Comment by snim2** [comment]
There is an interesting link between this Issue and #9 - if a dataset can be uniquely identified, e.g. via a DOI, is that sufficient, or does there need to be a way to verify that the dataset contains exactly the data that the author deposited? e.g. should there be an `md5` hash that goes with the data that can be used to verify its origin?
