### ISSUE TITLE
Proposed Workflow

### ISSUE THREAD

**Issue by emhart** [emhart/10-simple-rules-data-storage#7]
Hi Everyone,

Wanted to use this issue to talk about a workflow.  My current thinking is that we can just open each idea as for a proposed rule and discuss and debate it in the body of the issue.  Proposed issues can be labeled as such (I've created this label) and then as we come to agreement, the label will be changed to accepted and rejected rules will be closed.  

Once a set of rules is agreed upon we will assign 1 - 3 people per rule to write that section and commit it to the repo.  Anyone should be free to edit a given section as well.  

Other tasks that arise will be assigned on an as needed basis.

Does this sound like a reasonable approach?  Please toss out any other ideas you might have in this issue.  I personally like to have an agree upon workflow for a group of collaborators this large.  Thanks!

**Comment by jhollist** [comment]
@emhart and everyone,

That sounds good to me.  I too like having the ground rules set.

How will we be writing this up?  Markdown, latex, ... ?  I suppose this isn't workflow necessarily, but somewhat related.

**Comment by karawoo** [comment]
The workflow sounds good to me. :+1: 

I vote for writing in markdown.

**Comment by jhollist** [comment]
I second your markdown vote, @karawoo

**Comment by fmichonneau** [comment]
:+1: for the workflow and markdown.

**Comment by dlebauer** [comment]
Good approach, additions:
- I expect that many of the "rejected" rules may be rejected because of generality rather than that they are not good ideas - so it might be useful to transfer some of the content to a related rule at time of rejection.
- For a given rule, as the scope of the rule gets refined, and good ideas identified, update / ammend the rule in the original post. The goal would be for the rule to 'magically appear' at the top of the issue. 
  - _background:_ I haven't done this with rules, but with bugs/features often the desired outcome is very different from the original report (and title), but it takes a few bits of discussion (or more) to flush out the resolution. At that point it is much more effective to keep the top issue as a summary. That way when reading (for the first time or after an absence, or just looking at the title), the point is clear. Otherwise, following a discussion that may take place partially in other issues / pull requests / offline becomes very difficult.

_note_ this requires appropriate permissions

**Comment by naupaka** [comment]
+1 to md and issues

**Comment by tpoisot** [comment]
:+1: for markdown, :+1: for issues

**Comment by snim2** [comment]
This sounds like an excellent idea to me. +1

**Comment by snim2** [comment]
I'm aware that we are somewhat behind on the original schedule that was set out in Issue #24. I have some time available at the end of this week or the start of next, and I would be happy to go through this again. It isn't obvious to me from the Issues what still needs doing. Are we still at the review-and-suggest-edits stage or are there more specific contributions you would like people to make?

**Comment by emhart** [comment]
@snim2 At this point most of the text is written so there's no single issue that still needs to be written.  I think all that's really needed are for people to make any edits they want, and then I'm going to post to a pre-print server before we submit.  If you want to take a pass at it and the submit a PR with edits that would be great!

**Comment by gvwilson** [comment]
I'd be very happy to do an editing pass if I could get it to build on my 
Mac...
