### ISSUE TITLE
Datasets should be citable and uniquely identifiable

### ISSUE THREAD

**Issue by fmichonneau** [emhart/10-simple-rules-data-storage#9]

**Comment by dlebauer** [comment]
... how about 'should be both easy to find and uniquely identifiable?'

note that 'doi' is one of many ways of permanently identifying a digital object. Is the intent to specify doi?

**Comment by fmichonneau** [comment]
It seems that the "easy to find part" is a different issue that goes with where the data should be deposited. I will open an other rule for this one.

**Comment by emhart** [comment]
So I take it that by this you mean if a data set is stored across multiple repositories it has a unique ID.  Which begs the question, with a DOI, what is identified (Not that you're saying we should use DOI, but that's what most people will fall back to)?  The location + the data set, or just the data set regardless of location?

**Comment by dlebauer** [comment]
doi points to data set regardless of location. If the resource is moved, the location that the doi redirects to is updated (this isn't automated nor recommended).

**Comment by emhart** [comment]
To clarify my question I guess I'm saying, what if you have a data-set stored in multiple places?  Do you identify each instance? Let's say I post data on Figshare and Dryad, do I give each one a unique identifier because it's the same data in different locations?   

I don't mean to belabor a pedantic point, but I think it's important that we specify things like "data should be stored in just one publicly accessible place" or "Data can be stored across multiple repositories", and we should provide a best practice for how to identify data sets if it's the latter.

**Comment by emhart** [comment]
One more note on this topic is that it might be too close to Rule 2 in http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003542

**Comment by wcornwell** [comment]
An additional discussion point: seems like one thing that is happening more and more is living datasets that _should_ keep growing after publication (or being assembled into more and more comprehensive databases).  So it seems like we should give some guidance about dataset versioning, but not sure what the right rule for this is.  Any ideas?
