### ISSUE TITLE
author order

### ISSUE THREAD

**Issue by PBarmby** [emhart/10-simple-rules-data-storage#92]
Did we talk about this earlier? I don't recall and can't find it in the issues, but if I missed something feel free to ignore this.

As far as I know, conventions for author order are field-dependent. In my field (astronomy), author order usually reflects descending order of contribution; names are alphabetized if there's no distinction between the amount of contribution, and last author generally doesn't mean anything special.

If we want to order by contributions then should we just count commits? Lines of manuscript? I think @emhart should be first since he's been coordinating. Looking at the commit log, @gvwilson made a commit that did end up in the final text but is not currently listed as an author.

If we don't want contribution order, I'm perfectly happy with alphabetical, reverse alphabetical, alphabetical-by-middle-initial, or whatever other scheme anyone can dream up.

**Comment by naupaka** [comment]
I am fine with whatever order works for others, as long as @emhart is first. In ecology, last author is usually senior author (PI), with the rest of the order done by descending degree of contribution.

**Comment by tpoisot** [comment]
So going by number of lines added, I get
- Hart
- Hollister
- Michonneau
- Zimmerman
- Poisot
- LeBauer
- Mount
- Barmby
- Woo
- Cornwell
- Falster
- Turner
- Wilson

**Comment by jhollist** [comment]
Probably don't want me top three.  I'd have to pass the paper through
internal review prior to submission or pushing up to a pre-print server.
That could add 6 weeks (at best).

**Comment by emhart** [comment]
Hi all, I reached out to @gvwilson  about authorship yesterday and asked if he wanted a spot, and he declined.
Falster, Turner and Corwell all just add their contact info to the readme, but didn't actually commit anything to the text. (e.g. https://github.com/emhart/10-simple-rules-data-storage/commits?author=stephenturner)  So they were never added to the list of authors.

So going by @tpoisot list (and moving @jhollist around) it would look like this.  I'll make this change unless anyone objects.
- Hart
- Michonneau
- Zimmerman
- Hollister
- Poisot
- LeBauer
- Mount
- Barmby
- Woo

**Comment by dlebauer** [comment]
While the idea of using an 'objective' quantification of contribution is admirable, I respectfully propose that 'lines of code' is not a meaningful metric. Here is the value of individual contributions in units of 'lines of code':

| contribution | lines of code value |
| --- | --- |
| initiate effort | 0 |
| propose rule | 0 |
| comment on issue | 0 |
| fix typo | 1 |
| add name as author | 1 |
| add paragraph | 1 |
| add paragraph with line breaks | 5 |
| add citation to .bib file | 10 |
| add figure | 1000 |
| add template files | 3000 |

I don't know if there is any existing protocol for using such a metric, but I do not consider this valid or meaningful in the context of scientific contribution. I would prefer almost any other existing rubric for ranking authorship. If we do do this, we should have a clear statement of contributions _and_ the analysis used to rank the contributors.

My suggestion would be to follow the convention of lead author followed by an alphabetical list (the least contentious). And we should add Greg to the acknowledgements (the effort traces back to his swcarpentry/site#797 so I would otherwise suggest listing him last as senior author).

It is not even clear how the 'lines of code' metric is computed. Does it include pull requests that were not merged? Is it based on the [Github Graphs](https://github.com/emhart/10-simple-rules-data-storage/graphs/contributors?from=2015-02-15&to=2015-10-17&type=c)? 

<img width="468" alt="screen shot 2015-10-17 at 11 13 10 pm" src="https://cloud.githubusercontent.com/assets/464871/10562518/b3e8fb6e-7524-11e5-9cdc-ebc2dcdcee88.png">

Or perhaps `git-blame`?:

``` sh
git fame --bytype


+----------------------+-------+---------+-------+--------------------+---------+-----+-----+-----+------+-----+-----+
| name                 | loc   | commits | files | distribution       | unknown | md  | bib | csl | bst  | tex | eps |
+----------------------+-------+---------+-------+--------------------+---------+-----+-----+-----+------+-----+-----+
| Jeff Hollister       | 2,843 | 5       | 8     | 59.6 / 3.1 / 57.1  | 8       | 53  | 19  | 316 | 1882 | 565 | 0   |
| Francois Michonneau  | 1,014 | 35      | 4     | 21.3 / 21.7 / 28.6 | 0       | 173 | 45  | 0   | 0    | 0   | 796 |
| Ted Hart             | 350   | 11      | 2     | 7.3 / 6.8 / 14.3   | 0       | 13  | 337 | 0   | 0    | 0   | 0   |
| Edmund Hart          | 212   | 43      | 3     | 4.4 / 26.7 / 21.4  | 116     | 96  | 0   | 0   | 0    | 0   | 0   |
| Timothée Poisot      | 146   | 8       | 2     | 3.1 / 5.0 / 14.3   | 0       | 146 | 0   | 0   | 0    | 0   | 0   |
| snim2                | 60    | 10      | 5     | 1.3 / 6.2 / 35.7   | 31      | 7   | 22  | 0   | 0    | 0   | 0   |
| Jeffrey W. Hollister | 52    | 1       | 2     | 1.1 / 0.6 / 14.3   | 0       | 34  | 18  | 0   | 0    | 0   | 0   |
| Naupaka Zimmerman    | 47    | 10      | 2     | 1.0 / 6.2 / 14.3   | 1       | 46  | 0   | 0   | 0    | 0   | 0   |
| Kara Woo             | 13    | 7       | 4     | 0.3 / 4.3 / 28.6   | 0       | 8   | 1   | 0   | 0    | 4   | 0   |
| David LeBauer        | 13    | 9       | 1     | 0.3 / 5.6 / 7.1    | 0       | 13  | 0   | 0   | 0    | 0   | 0   |
| Pauline              | 10    | 4       | 2     | 0.2 / 2.5 / 14.3   | 0       | 1   | 9   | 0   | 0    | 0   | 0   |
| Sarah Mount          | 6     | 5       | 2     | 0.1 / 3.1 / 14.3   | 0       | 1   | 5   | 0   | 0    | 0   | 0   |
| wcornwell            | 1     | 2       | 1     | 0.0 / 1.2 / 7.1    | 0       | 1   | 0   | 0   | 0    | 0   | 0   |
| Stephen Turner       | 1     | 1       | 1     | 0.0 / 0.6 / 7.1    | 0       | 1   | 0   | 0   | 0    | 0   | 0   |
| Pauline Barmby       | 1     | 3       | 1     | 0.0 / 1.9 / 7.1    | 0       | 1   | 0   | 0   | 0    | 0   | 0   |
| Daniel Falster       | 1     | 1       | 1     | 0.0 / 0.6 / 7.1    | 0       | 1   | 0   | 0   | 0    | 0   | 0   |
| Greg Wilson          | 0     | 1       | 0     | 0.0 / 0.6 / 0.0    | 0       | 0   | 0   | 0   | 0    | 0   | 0   |
| Jeffrey W Hollister  | 0     | 4       | 0     | 0.0 / 2.5 / 0.0    | 0       | 0   | 0   | 0   | 0    | 0   | 0   |
| karawoo              | 0     | 1       | 0     | 0.0 / 0.6 / 0.0    | 0       | 0   | 0   | 0   | 0    | 0   | 0   |
+----------------------+-------+---------+-------+--------------------+---------+-----+-----+-----+------+-----+-----+
```

**Comment by dlebauer** [comment]
Also note that using 'lines of code' to rank authors would potentially require reordering after each revision. As a plus, this could be built into the makefile :8ball:

**Comment by naupaka** [comment]
Seems there are probably many ways to quantify contributions, but my sense is that any is probably ok, as long as Ted is first, and Jeff is not top 3. There's also good 'ol `sample()` :game_die:

**Comment by emhart** [comment]
Since there's some dispute about how best to quantify effort let's go with alphabetical order.  @dlebauer as far as @gvwilson this is the text from the beginning of the acknowledgements: 

> We would like to thank G. Wilson and the Software Carpentry instructor community for providing the initial inspiration for this paper and the discussion held at https://github.com/swcarpentry/site/issues/797. 

Feel free to amend that if you'd like to change the wording, but I wanted to thank Greg, all SWC instructors and reference the initial discussion thread in our manuscript.

@gvwilson It's still not too late if you want to be senior author :wink:
